packages:
  - apps/notashelf.dev
  - packages/wasm-utils/pkg
  - packages/astro-email-obfuscation
  - packages/vite-copyright-replace
  - packages/vite-purge-css

onlyBuiltDependencies:
  - sharp
  - wasm-pack
