packages:
  - apps/*
  - packages/*
  - content

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - sharp

peerDependencyRules:
  allowedVersions:
    eslint: "10"
    typescript: "6"
